// flow-typed signature: f6613a443f7d0709f15536ebc3c74f00
// flow-typed version: <<STUB>>/bootstrap.native-loader_v^1.0.7/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap.native-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap.native-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'bootstrap.native-loader/index' {
  declare module.exports: $Exports<'bootstrap.native-loader'>;
}
declare module 'bootstrap.native-loader/index.js' {
  declare module.exports: $Exports<'bootstrap.native-loader'>;
}
