// flow-typed signature: 7391f1df7bc47b3d6068dc0249d06cda
// flow-typed version: <<STUB>>/bootstrap.native_v^2.0.22/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap.native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap.native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap.native/build-module-v4' {
  declare module.exports: any;
}

declare module 'bootstrap.native/build-module' {
  declare module.exports: any;
}

declare module 'bootstrap.native/build-v4' {
  declare module.exports: any;
}

declare module 'bootstrap.native/build' {
  declare module.exports: any;
}

declare module 'bootstrap.native/dist/bootstrap-native-v4' {
  declare module.exports: any;
}

declare module 'bootstrap.native/dist/bootstrap-native-v4.min' {
  declare module.exports: any;
}

declare module 'bootstrap.native/dist/bootstrap-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/dist/bootstrap-native.min' {
  declare module.exports: any;
}

declare module 'bootstrap.native/dist/polyfill' {
  declare module.exports: any;
}

declare module 'bootstrap.native/dist/polyfill.min' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/helpers' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/affix-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/alert-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/button-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/carousel-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/collapse-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/dropdown-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/modal-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/popover-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/scrollspy-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/tab-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/tooltip-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/utils-init' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V3/utils' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V4/alert-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V4/button-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V4/carousel-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V4/collapse-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V4/dropdown-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V4/modal-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V4/popover-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V4/scrollspy-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V4/tab-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V4/tooltip-native' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V4/utils-init' {
  declare module.exports: any;
}

declare module 'bootstrap.native/lib/V4/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap.native/build-module-v4.js' {
  declare module.exports: $Exports<'bootstrap.native/build-module-v4'>;
}
declare module 'bootstrap.native/build-module.js' {
  declare module.exports: $Exports<'bootstrap.native/build-module'>;
}
declare module 'bootstrap.native/build-v4.js' {
  declare module.exports: $Exports<'bootstrap.native/build-v4'>;
}
declare module 'bootstrap.native/build.js' {
  declare module.exports: $Exports<'bootstrap.native/build'>;
}
declare module 'bootstrap.native/dist/bootstrap-native-v4.js' {
  declare module.exports: $Exports<'bootstrap.native/dist/bootstrap-native-v4'>;
}
declare module 'bootstrap.native/dist/bootstrap-native-v4.min.js' {
  declare module.exports: $Exports<'bootstrap.native/dist/bootstrap-native-v4.min'>;
}
declare module 'bootstrap.native/dist/bootstrap-native.js' {
  declare module.exports: $Exports<'bootstrap.native/dist/bootstrap-native'>;
}
declare module 'bootstrap.native/dist/bootstrap-native.min.js' {
  declare module.exports: $Exports<'bootstrap.native/dist/bootstrap-native.min'>;
}
declare module 'bootstrap.native/dist/polyfill.js' {
  declare module.exports: $Exports<'bootstrap.native/dist/polyfill'>;
}
declare module 'bootstrap.native/dist/polyfill.min.js' {
  declare module.exports: $Exports<'bootstrap.native/dist/polyfill.min'>;
}
declare module 'bootstrap.native/lib/helpers.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/helpers'>;
}
declare module 'bootstrap.native/lib/V3/affix-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/affix-native'>;
}
declare module 'bootstrap.native/lib/V3/alert-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/alert-native'>;
}
declare module 'bootstrap.native/lib/V3/button-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/button-native'>;
}
declare module 'bootstrap.native/lib/V3/carousel-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/carousel-native'>;
}
declare module 'bootstrap.native/lib/V3/collapse-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/collapse-native'>;
}
declare module 'bootstrap.native/lib/V3/dropdown-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/dropdown-native'>;
}
declare module 'bootstrap.native/lib/V3/modal-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/modal-native'>;
}
declare module 'bootstrap.native/lib/V3/popover-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/popover-native'>;
}
declare module 'bootstrap.native/lib/V3/scrollspy-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/scrollspy-native'>;
}
declare module 'bootstrap.native/lib/V3/tab-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/tab-native'>;
}
declare module 'bootstrap.native/lib/V3/tooltip-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/tooltip-native'>;
}
declare module 'bootstrap.native/lib/V3/utils-init.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/utils-init'>;
}
declare module 'bootstrap.native/lib/V3/utils.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V3/utils'>;
}
declare module 'bootstrap.native/lib/V4/alert-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V4/alert-native'>;
}
declare module 'bootstrap.native/lib/V4/button-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V4/button-native'>;
}
declare module 'bootstrap.native/lib/V4/carousel-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V4/carousel-native'>;
}
declare module 'bootstrap.native/lib/V4/collapse-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V4/collapse-native'>;
}
declare module 'bootstrap.native/lib/V4/dropdown-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V4/dropdown-native'>;
}
declare module 'bootstrap.native/lib/V4/modal-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V4/modal-native'>;
}
declare module 'bootstrap.native/lib/V4/popover-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V4/popover-native'>;
}
declare module 'bootstrap.native/lib/V4/scrollspy-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V4/scrollspy-native'>;
}
declare module 'bootstrap.native/lib/V4/tab-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V4/tab-native'>;
}
declare module 'bootstrap.native/lib/V4/tooltip-native.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V4/tooltip-native'>;
}
declare module 'bootstrap.native/lib/V4/utils-init.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V4/utils-init'>;
}
declare module 'bootstrap.native/lib/V4/utils.js' {
  declare module.exports: $Exports<'bootstrap.native/lib/V4/utils'>;
}
