// flow-typed signature: 7fea0a0edc3c089bc98d41dda273d6ad
// flow-typed version: <<STUB>>/flow-runtime-cli_v^0.17.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-runtime-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-runtime-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-runtime-cli/example/example-1' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/example/typedefs' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-builtins/bom' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-builtins/core' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-builtins/cssom' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-builtins/dom' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-builtins/indexeddb' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-builtins/node' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-builtins/react-dom' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-builtins/react' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-builtins/serviceworkers' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-builtins/streams' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-runtime-cli' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/Aphrodite' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/mocha' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/babel-plugin-external-helpers_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/babel-plugin-flow-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/babel-plugin-transform-decorators-legacy_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/bluebird_v3.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/double-ended-queue_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/flow-config-parser_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/flow-parser_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/flow-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/minimist_v1.x.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/flow-typed/npm/mocha_v3.1.x' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/__tests__/generateDefinitions.test' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/buildProgram' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/collectExternalTypeReferences' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/commands/GenerateCommand' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/commands/ListDefinitionsCommand' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/commands/ListTypesCommand' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/crawlTypeDefinitions' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/crawlTypeDependencies' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/fastTraverse' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/findFiles' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/generateDefinitions' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/Graph/FlowEntity' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/Graph/FlowModule' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/Graph/index' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/importAST' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/index' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/loadFlowConfig' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/parseFile' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/parseFileWithFlow' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/shouldIgnoreType' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/typedefs' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/lib/util' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/__tests__/generateDefinitions.test' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/buildProgram' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/collectExternalTypeReferences' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/commands/GenerateCommand' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/commands/ListDefinitionsCommand' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/commands/ListTypesCommand' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/crawlTypeDefinitions' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/crawlTypeDependencies' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/fastTraverse' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/findFiles' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/generateDefinitions' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/Graph/FlowEntity' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/Graph/FlowModule' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/Graph/index' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/importAST' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/index' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/loadFlowConfig' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/parseFile' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/parseFileWithFlow' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/shouldIgnoreType' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/typedefs' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/src/util' {
  declare module.exports: any;
}

declare module 'flow-runtime-cli/test-polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-runtime-cli/example/example-1.js' {
  declare module.exports: $Exports<'flow-runtime-cli/example/example-1'>;
}
declare module 'flow-runtime-cli/example/typedefs.js' {
  declare module.exports: $Exports<'flow-runtime-cli/example/typedefs'>;
}
declare module 'flow-runtime-cli/flow-builtins/bom.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-builtins/bom'>;
}
declare module 'flow-runtime-cli/flow-builtins/core.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-builtins/core'>;
}
declare module 'flow-runtime-cli/flow-builtins/cssom.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-builtins/cssom'>;
}
declare module 'flow-runtime-cli/flow-builtins/dom.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-builtins/dom'>;
}
declare module 'flow-runtime-cli/flow-builtins/indexeddb.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-builtins/indexeddb'>;
}
declare module 'flow-runtime-cli/flow-builtins/node.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-builtins/node'>;
}
declare module 'flow-runtime-cli/flow-builtins/react-dom.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-builtins/react-dom'>;
}
declare module 'flow-runtime-cli/flow-builtins/react.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-builtins/react'>;
}
declare module 'flow-runtime-cli/flow-builtins/serviceworkers.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-builtins/serviceworkers'>;
}
declare module 'flow-runtime-cli/flow-builtins/streams.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-builtins/streams'>;
}
declare module 'flow-runtime-cli/flow-runtime-cli.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-runtime-cli'>;
}
declare module 'flow-runtime-cli/flow-typed/Aphrodite.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/Aphrodite'>;
}
declare module 'flow-runtime-cli/flow-typed/mocha.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/mocha'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/babel-plugin-external-helpers_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/babel-plugin-external-helpers_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/babel-plugin-flow-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/babel-plugin-flow-runtime_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/babel-plugin-transform-decorators-legacy_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/babel-plugin-transform-decorators-legacy_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/bluebird_v3.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/bluebird_v3.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/double-ended-queue_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/double-ended-queue_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/flow-config-parser_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/flow-config-parser_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/flow-parser_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/flow-parser_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/flow-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/flow-runtime_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/minimist_v1.x.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/minimist_v1.x.x'>;
}
declare module 'flow-runtime-cli/flow-typed/npm/mocha_v3.1.x.js' {
  declare module.exports: $Exports<'flow-runtime-cli/flow-typed/npm/mocha_v3.1.x'>;
}
declare module 'flow-runtime-cli/lib/__tests__/generateDefinitions.test.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/__tests__/generateDefinitions.test'>;
}
declare module 'flow-runtime-cli/lib/buildProgram.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/buildProgram'>;
}
declare module 'flow-runtime-cli/lib/collectExternalTypeReferences.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/collectExternalTypeReferences'>;
}
declare module 'flow-runtime-cli/lib/commands/GenerateCommand.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/commands/GenerateCommand'>;
}
declare module 'flow-runtime-cli/lib/commands/ListDefinitionsCommand.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/commands/ListDefinitionsCommand'>;
}
declare module 'flow-runtime-cli/lib/commands/ListTypesCommand.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/commands/ListTypesCommand'>;
}
declare module 'flow-runtime-cli/lib/crawlTypeDefinitions.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/crawlTypeDefinitions'>;
}
declare module 'flow-runtime-cli/lib/crawlTypeDependencies.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/crawlTypeDependencies'>;
}
declare module 'flow-runtime-cli/lib/fastTraverse.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/fastTraverse'>;
}
declare module 'flow-runtime-cli/lib/findFiles.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/findFiles'>;
}
declare module 'flow-runtime-cli/lib/generateDefinitions.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/generateDefinitions'>;
}
declare module 'flow-runtime-cli/lib/Graph/FlowEntity.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/Graph/FlowEntity'>;
}
declare module 'flow-runtime-cli/lib/Graph/FlowModule.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/Graph/FlowModule'>;
}
declare module 'flow-runtime-cli/lib/Graph/index.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/Graph/index'>;
}
declare module 'flow-runtime-cli/lib/importAST.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/importAST'>;
}
declare module 'flow-runtime-cli/lib/index.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/index'>;
}
declare module 'flow-runtime-cli/lib/loadFlowConfig.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/loadFlowConfig'>;
}
declare module 'flow-runtime-cli/lib/parseFile.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/parseFile'>;
}
declare module 'flow-runtime-cli/lib/parseFileWithFlow.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/parseFileWithFlow'>;
}
declare module 'flow-runtime-cli/lib/shouldIgnoreType.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/shouldIgnoreType'>;
}
declare module 'flow-runtime-cli/lib/typedefs.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/typedefs'>;
}
declare module 'flow-runtime-cli/lib/util.js' {
  declare module.exports: $Exports<'flow-runtime-cli/lib/util'>;
}
declare module 'flow-runtime-cli/src/__tests__/generateDefinitions.test.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/__tests__/generateDefinitions.test'>;
}
declare module 'flow-runtime-cli/src/buildProgram.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/buildProgram'>;
}
declare module 'flow-runtime-cli/src/collectExternalTypeReferences.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/collectExternalTypeReferences'>;
}
declare module 'flow-runtime-cli/src/commands/GenerateCommand.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/commands/GenerateCommand'>;
}
declare module 'flow-runtime-cli/src/commands/ListDefinitionsCommand.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/commands/ListDefinitionsCommand'>;
}
declare module 'flow-runtime-cli/src/commands/ListTypesCommand.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/commands/ListTypesCommand'>;
}
declare module 'flow-runtime-cli/src/crawlTypeDefinitions.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/crawlTypeDefinitions'>;
}
declare module 'flow-runtime-cli/src/crawlTypeDependencies.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/crawlTypeDependencies'>;
}
declare module 'flow-runtime-cli/src/fastTraverse.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/fastTraverse'>;
}
declare module 'flow-runtime-cli/src/findFiles.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/findFiles'>;
}
declare module 'flow-runtime-cli/src/generateDefinitions.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/generateDefinitions'>;
}
declare module 'flow-runtime-cli/src/Graph/FlowEntity.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/Graph/FlowEntity'>;
}
declare module 'flow-runtime-cli/src/Graph/FlowModule.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/Graph/FlowModule'>;
}
declare module 'flow-runtime-cli/src/Graph/index.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/Graph/index'>;
}
declare module 'flow-runtime-cli/src/importAST.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/importAST'>;
}
declare module 'flow-runtime-cli/src/index.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/index'>;
}
declare module 'flow-runtime-cli/src/loadFlowConfig.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/loadFlowConfig'>;
}
declare module 'flow-runtime-cli/src/parseFile.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/parseFile'>;
}
declare module 'flow-runtime-cli/src/parseFileWithFlow.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/parseFileWithFlow'>;
}
declare module 'flow-runtime-cli/src/shouldIgnoreType.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/shouldIgnoreType'>;
}
declare module 'flow-runtime-cli/src/typedefs.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/typedefs'>;
}
declare module 'flow-runtime-cli/src/util.js' {
  declare module.exports: $Exports<'flow-runtime-cli/src/util'>;
}
declare module 'flow-runtime-cli/test-polyfill.js' {
  declare module.exports: $Exports<'flow-runtime-cli/test-polyfill'>;
}
