// flow-typed signature: 93b053ca7db86cf611ee2b5c14d20e62
// flow-typed version: <<STUB>>/winstrap_v^0.5.11/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winstrap/dist/js/vendor/bootstrap.min' {
  declare module.exports: any;
}

declare module 'winstrap/dist/js/vendor/jquery.min' {
  declare module.exports: any;
}

declare module 'winstrap/Gruntfile' {
  declare module.exports: any;
}

declare module 'winstrap/handlebars-helpers/inArrayJson' {
  declare module.exports: any;
}

declare module 'winstrap/src/js/app' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winstrap/dist/js/vendor/bootstrap.min.js' {
  declare module.exports: $Exports<'winstrap/dist/js/vendor/bootstrap.min'>;
}
declare module 'winstrap/dist/js/vendor/jquery.min.js' {
  declare module.exports: $Exports<'winstrap/dist/js/vendor/jquery.min'>;
}
declare module 'winstrap/Gruntfile.js' {
  declare module.exports: $Exports<'winstrap/Gruntfile'>;
}
declare module 'winstrap/handlebars-helpers/inArrayJson.js' {
  declare module.exports: $Exports<'winstrap/handlebars-helpers/inArrayJson'>;
}
declare module 'winstrap/src/js/app.js' {
  declare module.exports: $Exports<'winstrap/src/js/app'>;
}
